#!/usr/bin/env python3
"""Generate every number, table body and figure in the paper from stored result files.

    python scripts/make_paper_artifacts.py --results results --out paper/generated
    python scripts/make_paper_artifacts.py --check      # fail if generated files would change

Deterministic: reads only result files in the repository and performs no training or
evaluation. Every number comes from stored results of runs made before the correction (GitHub, the
Hugging Face model card, or earlier local run records); nothing is computed anew. Numbers are
reported exactly as the repository's public result files (and the Hugging Face model cards) state them (stated once in the paper):
  * VEXMLM downstream scores are the strings in results/downstream_task_metrics.csv
    (NER/SA accuracy and F1 as fractions, 4 decimals; QA EM/F1 in %, 2 decimals), and
    ablation scores and deltas the strings in results/table5_ablation.csv (%, 2 decimals);
    both are re-checked against the per-seed result files;
  * the single-seed XLM-R baseline uses the same unit and precision as the matching VEXMLM value;
  * differences are computed from unrounded means, as in the repository's tables;
  * tokenizer metrics have 4 decimals, as in results/spmerge_tokenizer_metrics.json.
"""
import argparse
import csv
import json
import re
import statistics as st
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

SEEDS = (42, 43, 44, 45, 46)
TOKENIZER_LABELS = {
    "xlm-roberta-base": "XLM-R",
    "cis-lmu/glot500-base": "Glot500",
    "checkpoints/vexmlm-stage1-spm": "VEXMLM",
}
LANG_LABELS = {"amh": "Amharic", "tir": "Tigrinya"}
# Categorical slots 1-3 of the validated reference palette; hatching keeps the
# series distinguishable in greyscale print.
SERIES_STYLE = {
    "XLM-R": ("#2a78d6", ""),
    "Glot500": ("#eb6834", "//"),
    "VEXMLM": ("#1baf7a", ".."),
}
# (task row, dataset, metric key in results json, csv metric label, lang)
DOWNSTREAM = [
    ("SA", "afrisenti", "test_accuracy", "Accuracy", "amh"),
    ("NER", "masakhaner_amh", "test_accuracy", "Accuracy", "amh"),
    ("NER", "tigrinya_ner", "test_accuracy", "Accuracy", "tir"),
    ("QAEM", "amqa", "exact_match", "EM", "amh"),
    ("QAEM", "tigqa", "exact_match", "EM", "tir"),
    ("QAFone", "amqa", "f1", "F1", "amh"),
    ("QAFone", "tigqa", "f1", "F1", "tir"),
]
APPENDIX = [
    ("SA", "afrisenti", "test_macro_f1", "Macro-F1", "amh"),
    ("NER", "masakhaner_amh", "test_macro_f1", "Macro-F1", "amh"),
    ("NER", "tigrinya_ner", "test_macro_f1", "Macro-F1", "tir"),
    ("NER", "masakhaner_amh", "test_entity_f1", "Entity-F1", "amh"),
    ("NER", "tigrinya_ner", "test_entity_f1", "Entity-F1", "tir"),
]
ABLATION_ARMS = ["xlmr_baseline", "expansion_random_init", "expansion_mean_init", "full_vexmlm"]
ABLATION_LABELS = ["XLM-R baseline", "+ VocabExp (Random Init)", "+ VocabExp (Mean Init)",
                   "+ Continued Pretraining (VEXMLM)"]
DEC = {"fertility": 4, "compression": 4, "roundtrip": 4}


class Macros:
    def __init__(self):
        self.lines = ["% Generated by scripts/make_paper_artifacts.py -- do not edit.", ""]
        self.values = {}

    def add(self, name, value, source):
        if not name.isalpha():
            raise ValueError(f"LaTeX macro names must be letters only: {name}")
        if name in self.values:
            raise ValueError(f"duplicate macro {name}")
        self.values[name] = value
        self.lines.append(f"\\newcommand{{\\{name}}}{{{value}}}  % {source}")

    def text(self):
        return "\n".join(self.lines) + "\n"


def fmt_ms(vals, dec=2):
    return f"{st.mean(vals):.{dec}f} $\\pm$ {st.stdev(vals):.{dec}f}"


def tex_pm(csv_value):
    return csv_value.replace(" ± ", " $\\pm$ ")


def lang_macro(lang):
    return {"amh": "Amh", "tir": "Tir"}[lang]


# ------------------------------------------------------------------ tokenizer
TOKENIZER_SOURCES = {
    # Stored results of earlier runs of evaluation/run_intrinsic.py on the same dev/OOV files.
    "xlm-roberta-base": "spmerge_tokenizer_metrics.json",                   # on GitHub
    "checkpoints/vexmlm-stage1-spm": "spmerge_tokenizer_metrics.json",      # on GitHub
    "cis-lmu/glot500-base": "provenance/tokenizer_metrics_2026-08-15.json",  # earlier local run
}


def load_tokenizer_metrics(results: Path) -> dict:
    rows = {}
    for key, label in TOKENIZER_LABELS.items():
        t = json.loads((results / TOKENIZER_SOURCES[key]).read_text())["tokenizers"][key]
        rows[label] = {
            lang: {
                "fertility": t["per_language"][lang]["fertility"],
                "compression": t["per_language"][lang]["compression"],
                "roundtrip": t["oov"][lang]["roundtrip_rate"],
            }
            for lang in LANG_LABELS
        }
    return rows


def tokenizer_artifacts(rows, macros, out):
    src = "results/spmerge_tokenizer_metrics.json (Glot500: results/provenance/tokenizer_metrics_2026-08-15.json)"
    short = {"XLM-R": "Xlmr", "Glot500": "Glot", "VEXMLM": "Vex"}
    for model, per_lang in rows.items():
        for lang, m in per_lang.items():
            for metric, v in m.items():
                name = f"tok{short[model]}{lang_macro(lang)}{metric.capitalize()}"
                macros.add(name, f"{v:.{DEC[metric]}f}", f"{src} {model} {lang} {metric}={v}")
    for lang in LANG_LABELS:
        x, v = rows["XLM-R"][lang]["fertility"], rows["VEXMLM"][lang]["fertility"]
        macros.add(f"tokFertRed{lang_macro(lang)}", f"{100 * (x - v) / x:.1f}",
                   f"{src} (XLM-R - VEXMLM) / XLM-R fertility, {lang}")
    body = []
    for metric, label in [("fertility", "Fertility $\\downarrow$"),
                          ("compression", "Compression $\\uparrow$"),
                          ("roundtrip", "Round-trip $\\uparrow$")]:
        for i, lang in enumerate(LANG_LABELS):
            cells = [f"{rows[mdl][lang][metric]:.{DEC[metric]}f}" for mdl in TOKENIZER_LABELS.values()]
            best = (min if metric == "fertility" else max)(float(c) for c in cells)
            cells = [f"\\textbf{{{c}}}" if float(c) == best and metric != "roundtrip" else c
                     for c in cells]
            body.append(f"{label if i == 0 else ''} & {LANG_LABELS[lang]} & " + " & ".join(cells) + r" \\")
    (out / "table_tokenizer.tex").write_text("\n".join(body) + "\n")
    figure_fertility(rows, out / "fig_fertility.pdf")


def figure_fertility(rows: dict, out: Path) -> None:
    plt.rcParams.update({"font.family": "serif", "font.size": 9,
                         "axes.spines.top": False, "axes.spines.right": False,
                         "pdf.fonttype": 42})
    fig, ax = plt.subplots(figsize=(3.3, 2.3))
    langs = list(LANG_LABELS)
    width = 0.26
    for i, (model, (color, hatch)) in enumerate(SERIES_STYLE.items()):
        xs = [j + (i - 1) * (width + 0.02) for j in range(len(langs))]
        vals = [rows[model][lang]["fertility"] for lang in langs]
        bars = ax.bar(xs, vals, width, label=model, color=color, hatch=hatch,
                      edgecolor="white", linewidth=0.8)
        for b, v in zip(bars, vals):
            ax.text(b.get_x() + b.get_width() / 2, v + 0.04, f"{v:.4f}",
                    ha="center", va="bottom", fontsize=5.5, color="#333333")
    ax.set_xticks(range(len(langs)), [LANG_LABELS[lang] for lang in langs])
    ax.set_ylabel("Fertility (tokens per word)")
    ax.set_ylim(0, 3.6)
    ax.yaxis.grid(True, color="#e5e5e5", linewidth=0.6)
    ax.set_axisbelow(True)
    ax.legend(frameon=False, fontsize=7.5, ncol=3, loc="lower center",
              bbox_to_anchor=(0.5, 1.0))
    fig.tight_layout()
    fig.savefig(out, bbox_inches="tight", metadata={"CreationDate": None, "ModDate": None})
    plt.close(fig)


# ----------------------------------------------------------------- downstream
def vexmlm_runs(results: Path, dataset: str, key: str) -> list:
    return [json.loads((results / "spm_stage2" / f"{dataset}-seed{s}.json").read_text())["metrics"][key]
            for s in SEEDS]


def xlmr_run(results: Path, dataset: str, key: str) -> float:
    m = json.loads((results / "baselines" / "xlmr_seed42" / dataset / "results.json").read_text())
    return m["metrics"][key]


def published(results: Path, dataset, label, vals):
    """The CSV string for (dataset, metric), after checking it against the per-seed runs."""
    with open(results / "downstream_task_metrics.csv") as f:
        for row in csv.DictReader(f):
            if row["Dataset"] == dataset and row["Metric"] == label:
                value = row["VEXMLM SP-Merge (mean ± std)"]
                mean_s, sd_s = value.split(" ± ")
                dec = len(mean_s.split(".")[1])
                if f"{st.mean(vals):.{dec}f}" != mean_s or f"{st.stdev(vals):.{dec}f}" != sd_s:
                    raise SystemExit(f"per-seed runs disagree with downstream_task_metrics.csv: {dataset} {label}")
                return value, dec
    raise SystemExit(f"{dataset} {label} missing from downstream_task_metrics.csv")


def downstream_artifacts(results, macros, out):
    def rows_for(spec, prefix):
        lines = []
        for task, dataset, key, label, lang in spec:
            vex = vexmlm_runs(results, dataset, key)
            value, dec = published(results, dataset, label, vex)
            base = xlmr_run(results, dataset, key)
            metric_tag = "" if prefix == "ds" else "".join(c for c in label if c.isalpha())
            m = f"{prefix}{task}{metric_tag}{lang_macro(lang)}"
            src_v = f"results/downstream_task_metrics.csv {dataset} {label} (= results/spm_stage2/{dataset}-seed42..46.json metrics.{key})"
            src_x = f"results/baselines/xlmr_seed42/{dataset}/results.json metrics.{key}"
            macros.add(f"{m}Vex", tex_pm(value), src_v)
            macros.add(f"{m}Xlmr", f"{base:.{dec}f}", src_x)
            diff = st.mean(vex) - base
            within = abs(diff) <= st.stdev(vex)
            macros.add(f"{m}Diff", f"{diff:+.{dec}f}", f"VEXMLM mean - XLM-R, unrounded ({'within' if within else 'beyond'} 1 sd)")
            macros.add(f"{m}DiffAbs", f"{abs(diff):.{dec}f}", "magnitude of the difference above")
            lines.append((task, dataset, label, lang, f"{base:.{dec}f}", tex_pm(value), within, st.mean(vex) > base))
        return lines

    ds_name = {"afrisenti": "AfriSenti", "masakhaner_amh": "MasakhaNER", "tigrinya_ner": "Tigrinya NER",
               "amqa": "AmQA", "tigqa": "TIGQA"}
    task_label = {"SA": "SA (Accuracy)", "NER": "NER (Accuracy)", "QAEM": "QA (EM, \\%)", "QAFone": "QA (F1, \\%)"}

    def emit(lines, fname, label_of):
        body, last = [], None
        for task, dataset, label, lang, xcell, vcell, within, vex_higher in lines:
            head = label_of(task, label) if (task, label) != last else ""
            last = (task, label)
            if not within:
                if vex_higher:
                    vcell = f"\\textbf{{{vcell}}}"
                else:
                    xcell = f"\\textbf{{{xcell}}}"
            body.append(f"{head} & {ds_name[dataset]} ({LANG_LABELS[lang]}) & {xcell} & {vcell} \\\\")
        (out / fname).write_text("\n".join(body) + "\n")

    emit(rows_for(DOWNSTREAM, "ds"), "table_downstream.tex", lambda t, l: task_label[t])
    emit(rows_for(APPENDIX, "app"), "table_appendix_f1.tex",
         lambda t, l: f"{'SA' if t == 'SA' else 'NER'} ({l})")


# ------------------------------------------------------------------- ablation
def ablation_artifacts(results, macros, out):
    means, rows = [], []
    with open(results / "table5_ablation.csv") as f:
        committed = {r["Arm"]: r for r in csv.DictReader(f)}
    csrc5 = "results/table5_ablation.csv"
    for arm, label in zip(ABLATION_ARMS, ABLATION_LABELS):
        ms = [json.loads((results / "ablation" / f"{arm}-seed{s}.json").read_text())["metrics"]
              for s in SEEDS]
        oov = [m["oov_accuracy"] for m in ms]
        non = [m["non_oov_accuracy"] for m in ms]
        value = committed[arm]["OOV Accuracy (%) mean ± std"]
        if f"{st.mean(oov):.2f} ± {st.stdev(oov):.2f}" != value:
            raise SystemExit(f"per-seed runs disagree with table5_ablation.csv: {arm}")
        means.append(st.mean(oov))
        rows.append((label, tex_pm(value), committed[arm]["Delta"], oov, non))
        name = {"xlmr_baseline": "Base", "expansion_random_init": "Rand",
                "expansion_mean_init": "Mean", "full_vexmlm": "Full"}[arm]
        macros.add(f"abl{name}", tex_pm(value), f"{csrc5} {arm}")
        macros.add(f"abl{name}NonOOV", fmt_ms(non), f"results/ablation/{arm}-seed42..46.json metrics.non_oov_accuracy")
        if committed[arm]["Delta"]:
            d = committed[arm]["Delta"]
            if f"{means[-1] - means[-2]:+.2f}" != d:
                raise SystemExit(f"table5_ablation.csv Delta disagrees with per-seed runs: {arm}")
            macros.add(f"abl{name}Delta", d, f"{csrc5} {arm} Delta (from unrounded means)")
            macros.add(f"abl{name}DeltaAbs", d.lstrip("+-"), "magnitude of the difference above")
    macros.add("ablFullVsBase", f"{means[-1] - means[0]:+.2f}", "full_vexmlm - xlmr_baseline, unrounded means")
    body = []
    for label, cell, delta, _, _ in rows:
        if label.startswith("+ Continued"):
            cell = f"\\textbf{{{cell}}}"
        body.append(f"{label} & {cell} & {delta or '--'} \\\\")
    (out / "table_ablation.tex").write_text("\n".join(body) + "\n")
    # Table 3 slot: accuracy on other / fragmented words, XLM-R vs full VEXMLM, Tigrinya only.
    base, full = rows[0], rows[-1]
    macros.add("oovGainTir", f"{st.mean(full[3]) - st.mean(base[3]):+.2f}",
               "full_vexmlm - xlmr_baseline mean oov_accuracy, unrounded")
    macros.add("nonOOVGainTir", f"{st.mean(full[4]) - st.mean(base[4]):+.2f}",
               "full_vexmlm - xlmr_baseline mean non_oov_accuracy, unrounded")
    (out / "table_oov.tex").write_text(
        f"Tigrinya & {fmt_ms(base[4])} & {base[1]} & {fmt_ms(full[4])} & "
        f"\\textbf{{{full[1]}}} \\\\\n")
    data = json.loads((results / "ablation" / "full_vexmlm-seed42.json").read_text())
    macros.add("ablOOVTypes", f"{data['oov_word_types']:,}".replace(",", "{,}"),
               "results/ablation/full_vexmlm-seed42.json oov_word_types")
    macros.add("ablWordTypes", f"{data['word_types']:,}".replace(",", "{,}"),
               "results/ablation/full_vexmlm-seed42.json word_types")


def _num(n) -> str:
    return f"{n:,}".replace(",", "{,}")


def fact_macros(results, macros):
    prov = results / "provenance"
    load = lambda p: json.loads(p.read_text())  # noqa: E731

    card = (prov / "hf_model_card_Hailay_VEXMLM.md").read_text()
    csrc = "results/provenance/hf_model_card_Hailay_VEXMLM.md (Hugging Face card Hailay/VEXMLM)"
    params = re.search(r"\| Parameters \| ([\d,]+) \|", card).group(1)
    vocab = re.search(r"\| Vocabulary \| \*\*([\d,]+)\*\* \(([\d,]+) base", card)
    macros.add("paramVex", params.replace(",", "{,}"), csrc + " Parameters")
    macros.add("vocabFinal", vocab.group(1).replace(",", "{,}"), csrc + " Vocabulary")
    macros.add("vocabBase", vocab.group(2).replace(",", "{,}"), csrc + " Vocabulary (base)")

    rman = load(prov / "expansion_manifest_spm_random.json")["initialization"]
    macros.add("randInitStd", f"{rman['old_perdim_std']:.2f}",
               "results/provenance/expansion_manifest_spm_random.json initialization.old_perdim_std")
    man = load(prov / "expansion_manifest_spm.json")
    macros.add("vocabAdded", _num(man["tokens_added"]), "results/provenance/expansion_manifest_spm.json tokens_added")

    for lang, code in (("amh", "Amh"), ("tir", "Tir")):
        tm = load(prov / f"tokenizer_manifest_{lang}.json")
        macros.add(f"spm{code}Vocab", _num(tm["spec"]["vocab_size"]), f"tokenizer_manifest_{lang}.json spec.vocab_size")
        macros.add(f"spm{code}TrainLines", _num(tm["corpus"]["lines_read"]), f"tokenizer_manifest_{lang}.json corpus.lines_read")
        meta = load(prov / f"new_tokens_{lang}.json")["metadata"]
        macros.add(f"cand{code}Absent", _num(meta["candidates_total"] - meta["already_in_base"]),
                   f"new_tokens_{lang}.json candidates_total - already_in_base")
        macros.add(f"cand{code}Selected", _num(meta["selected"]), f"new_tokens_{lang}.json selected")
    tm = load(prov / "tokenizer_manifest_amh.json")["spec"]
    macros.add("spmCharCoverage", f"{tm['character_coverage']}", "tokenizer_manifest_amh.json spec.character_coverage")

    lists = {}
    for lang in ("amh", "tir"):
        d = load(prov / f"new_tokens_{lang}.json")
        lists[lang] = {t["token"] if isinstance(t, dict) else t for t in d["tokens"]}
    chosen = set(load(prov / "new_tokens.json")["tokens"])
    a, t = lists["amh"], lists["tir"]
    macros.add("newOnlyAmh", _num(len(chosen & a - t)), "new_tokens.json vs new_tokens_amh.json")
    macros.add("newOnlyTir", _num(len(chosen & t - a)), "new_tokens.json vs new_tokens_tir.json")
    macros.add("newShared", _num(len(chosen & a & t)), "new_tokens.json in both candidate lists")

    prep = load(prov / "preparation_report.json")
    for lang, code in (("amharic", "Amh"), ("tigrinya", "Tir")):
        p = prep[lang]
        for key, name in (("lines_read", "Raw"), ("kept", "Kept"), ("train", "Train"),
                          ("dev", "Dev"), ("oov_words", "OOVWords")):
            macros.add(f"corpus{code}{name}", _num(p[key]), f"results/provenance/preparation_report.json {lang}.{key}")

    ts = load(prov / "stage1_spm_trainer_state_best.json")
    evals = [e for e in ts["log_history"] if "eval_loss" in e]
    best = min(evals, key=lambda e: e["eval_loss"])
    macros.add("ptBestEpoch", f"{best['epoch']:.0f}", "stage1_spm_trainer_state_best.json min eval_loss")
    macros.add("ptBestStep", _num(best["step"]), "stage1_spm_trainer_state_best.json min eval_loss")
    macros.add("ptBestLoss", f"{best['eval_loss']:.4f}", "stage1_spm_trainer_state_best.json min eval_loss")
    args = load(prov / "training_args.json")
    macros.add("ptEpochsConfigured", f"{args['stage1_spm']['num_train_epochs']}", "training_args.json stage1_spm")
    summ = load(prov / "stage1_summary_spm.json")
    macros.add("ptGPU", summ["hardware"]["device_names"][0], "stage1_summary_spm.json hardware")

    import yaml
    cfg = yaml.safe_load((results.parent / "configs" / "base.yaml").read_text())
    sci = lambda x: f"${x / 10 ** int(f'{x:e}'.split('e')[1]):g} \\times 10^{{{int(f'{x:e}'.split('e')[1])}}}$"  # noqa: E731
    for stage, key, run in (("pt", "pretraining", "stage1_spm"), ("ft", "finetuning", "finetune_amqa_seed42")):
        a = args[run]
        s = f"training_args.json {run}"
        macros.add(f"{stage}LR", sci(a["learning_rate"]), s)
        macros.add(f"{stage}Batch", f"{a['per_device_train_batch_size'] * a['gradient_accumulation_steps']}", s)
        macros.add(f"{stage}Warmup", f"{a['warmup_ratio'] * 100:g}\\%", s)
        macros.add(f"{stage}WeightDecay", f"{a['weight_decay']:g}", s)
        macros.add(f"{stage}Clip", f"{a['max_grad_norm']:.1f}", s)
        macros.add(f"{stage}Precision", "bf16" if a["bf16"] else ("fp16" if a["fp16"] else "fp32"), s)
        macros.add(f"{stage}AdamEps", sci(a["adam_epsilon"]), s)
        macros.add(f"{stage}AdamBetaOne", f"{a['adam_beta1']:g}", s)
        macros.add(f"{stage}AdamBetaTwo", f"{a['adam_beta2']:g}", s)
        macros.add(f"{stage}MaxLen", f"{cfg[key]['max_seq_length']}", f"configs/base.yaml {key}.max_seq_length")
    macros.add("ftEpochs", f"{args['finetune_amqa_seed42']['num_train_epochs']:g}", "training_args.json finetune_amqa_seed42")
    macros.add("ptMLMProb", f"{cfg['pretraining']['mlm_probability']:g}", "configs/base.yaml pretraining.mlm_probability")
    tag = {"afrisenti": "SA", "masakhaner_amh": "NERAmh", "tigrinya_ner": "NERTir", "amqa": "AmQA", "tigqa": "TigQA"}
    for ds, t in tag.items():
        meta = load(results.parent / "datasets" / "metadata" / f"{ds}.json")
        for split, info in meta["splits"].items():
            n = info["rows"] if isinstance(info, dict) else info
            macros.add(f"split{t}{split.capitalize()}", _num(n), f"datasets/metadata/{ds}.json splits.{split}.rows")

    log_text = (prov / "stage1_spm_data.log.txt").read_text()
    lsrc = "results/provenance/stage1_spm_data.log.txt"
    macros.add("ptAlpha", re.search(r"alpha=([0-9.]+)", log_text).group(1), lsrc)
    up = re.search(r"upsampled \(alpha=[0-9.]+\): amharic=(\d+) tigrinya=(\d+)", log_text)
    macros.add("ptSampledAmh", _num(int(up.group(1))), lsrc)
    macros.add("ptSampledTir", _num(int(up.group(2))), lsrc)
    tr = re.search(r"block-chunked train: (\d+) lines -> (\d+) blocks", log_text)
    va = re.search(r"block-chunked validation: (\d+) lines -> (\d+) blocks", log_text)
    macros.add("ptTrainLines", _num(int(tr.group(1))), lsrc)
    macros.add("ptTrainBlocks", _num(int(tr.group(2))), lsrc)
    macros.add("ptValLines", _num(int(va.group(1))), lsrc)
    macros.add("ptValBlocks", _num(int(va.group(2))), lsrc)


def build(results: Path, out: Path) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    macros = Macros()
    fact_macros(results, macros)
    tokenizer_artifacts(load_tokenizer_metrics(results), macros, out)
    downstream_artifacts(results, macros, out)
    ablation_artifacts(results, macros, out)
    (out / "results_macros.tex").write_text(macros.text())
    return macros.values


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", default="results", type=Path)
    ap.add_argument("--out", default="paper/generated", type=Path)
    ap.add_argument("--check", action="store_true",
                    help="regenerate into a temp dir and fail if any text artifact differs")
    args = ap.parse_args()
    if args.check:
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            build(args.results, Path(tmp))
            bad = [p.name for p in Path(tmp).glob("*.tex")
                   if not (args.out / p.name).exists()
                   or (args.out / p.name).read_text() != p.read_text()]
        if bad:
            sys.exit(f"stale generated artifacts: {bad}")
        print("generated artifacts are up to date")
        return
    values = build(args.results, args.out)
    print(f"wrote {len(values)} macros and tables to {args.out}")


if __name__ == "__main__":
    main()
